Adding release notes

diff --git a/.github/workflows/test_release_packages.yml b/.github/workflows/test_release_packages.yml
--- a/.github/workflows/test_release_packages.yml
+++ b/.github/workflows/test_release_packages.yml
@@ -6,25 +6,24 @@ on:
 
 jobs:
   generate_release_matrix:
-    runs-on: ubuntu-latest
+    runs-on: linux-mi300-1gpu-ossci-rocm
     outputs:
       release_matrix: ${{ steps.configure.outputs.release_matrix }}
     steps:
-      - name: "Checking out repository"
+      - name: Checking out repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: "Generating release matrix"
+      - name: Generating release matrix
         id: configure
         env:
           ASSET_FILES: ${{ toJSON(github.event.release.assets) }}
         run: python ./build_tools/configure_release_matrix.py
 
   test_release_packages:
-    runs-on: ubuntu-latest
+    runs-on: linux-mi300-1gpu-ossci-rocm
     needs: generate_release_matrix
     strategy:
       matrix:
-        # for now, we will only run tests on gfx942
         file_name: ${{ fromJSON(needs.generate_release_matrix.outputs.release_matrix) }}
     env:
       FILE_NAME: ${{ matrix.file_name }}
@@ -35,8 +34,9 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      # Downloading most triggered release tag assets to artifacts directory
-      - name: 'Download release artifacts'
+      # Downloading release tag assets to artifacts directory
+      # For now, we will only run tests on gfx942 since we only have one machine for gfx942
+      - name: Download release artifacts
         uses: robinraju/release-downloader@v1
         with:
           tag: ${{ env.TAG_NAME }}
@@ -45,13 +45,10 @@ jobs:
 
       - name: Extract tar asset file
         run: |
-          ls artifacts
           mkdir -p ${{ github.workspace }}/artifacts/output_dir
           tar -xf artifacts/${FILE_NAME} -C ${{ github.workspace }}/artifacts/output_dir
-          ls artifacts
-          ls artifacts/output_dir
 
-      - name: "Setting up Python"
+      - name: Setting up Python
         id: setup_python
         uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
         with:
@@ -64,21 +61,36 @@ jobs:
           pip install -r requirements-test.txt
 
       - name: Run Sanity check
+        if: '!cancelled()'
         run: |
           source ${VENV_DIR}/bin/activate
           pytest tests/ \
           --log-cli-level=info
+          echo "SANITY_CHECK_PASS=$(if [ $? -eq 0 ]; then echo PASS; else echo FAIL; fi)" >> $GITHUB_ENV
 
       - name: Run hipBLASLt tests
+        if: '!cancelled()'
         run: |
           source ${VENV_DIR}/bin/activate
           ${THEROCK_BIN_DIR}/hipblaslt-test --gtest_filter=*pre_checkin*
+          echo "HIPBLASLT_CHECK_PASS=$(if [ $? -eq 0 ]; then echo PASS; else echo FAIL; fi)" >> $GITHUB_ENV
 
       - name: Run rocBLAS tests
+        if: '!cancelled()'
         run: |
           ROCBLAS_TENSILE_LIBPATH="${THEROCK_BIN_DIR}/lib/rocblas/library/"
           source ${VENV_DIR}/bin/activate
           ${THEROCK_BIN_DIR}/rocblas-test --yaml ${THEROCK_BIN_DIR}/rocblas_smoke.yaml
+          echo "ROCBLAS_CHECK_PASS=$(if [ $? -eq 0 ]; then echo PASS; else echo FAIL; fi)" >> $GITHUB_ENV
 
-
-# add details to the release about tests
+      - name: Adding test notes to the release
+        if: '!cancelled()'
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: ${{ env.TAG_NAME }}
+          append_body: true
+          body: |
+            Test status:
+            * Sanity checks: ${SANITY_CHECK_PASS}
+            * hipBLASLt: ${HIPBLASLT_CHECK_PASS}
+            * rocBLAS: ${ROCBLAS_CHECK_PASS}
